/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Incg5764 (https://sketchfab.com/incg5764)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/new-year-present-box-e68ab6f9dbb44af7a1dcb37e4075ada8
title: New Year Present Box
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/new_year_present_box.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_6.geometry}
            material={materials.stripe}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_8.geometry}
            material={materials.flower}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/new_year_present_box.glb");