/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: FunFant (https://sketchfab.com/funfant)
license: CC-BY-ND-4.0 (http://creativecommons.org/licenses/by-nd/4.0/)
source: https://sketchfab.com/3d-models/present-1-low-poly-403cf4e5ce814903bd1fbde1d2da7122
title: Present 1 Low Poly
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/present_1_low_poly.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 4.09, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.christmas_present_Present_0.geometry}
              material={materials.Present}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/present_1_low_poly.glb");