/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: MesXwi (https://sketchfab.com/MesXwi)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/stylised-gifts-christmas-animated-321b080048b444bea63902d97cef99ba
title: Stylised Gifts Christmas - Animated
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/stylised_gifts_christmas_-_animated.glb"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="gift_anim_mesfbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Armature"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <group name="Object_21">
                    <primitive object={nodes._rootJoint} />
                    <group
                      name="Object_28"
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <skinnedMesh
                      name="Object_29"
                      geometry={nodes.Object_29.geometry}
                      material={materials["Cube_gift.003"]}
                      skeleton={nodes.Object_29.skeleton}
                      morphTargetDictionary={
                        nodes.Object_29.morphTargetDictionary
                      }
                      morphTargetInfluences={
                        nodes.Object_29.morphTargetInfluences
                      }
                    />
                  </group>
                </group>
                <group
                  name="Cube_gift007"
                  position={[-200, 100, 150]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube_gift007_Cube_gift007_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube_gift007_Cube_gift007_0.geometry}
                    material={materials["Cube_gift.007"]}
                  />
                </group>
                <group
                  name="Cube_gift006"
                  position={[-200, 100, 50]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube_gift006_Cube_gift006_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube_gift006_Cube_gift006_0.geometry}
                    material={materials["Cube_gift.006"]}
                  />
                </group>
                <group
                  name="Cube_gift005"
                  position={[-200, 100, -50]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube_gift005_Cube_gift005_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube_gift005_Cube_gift005_0.geometry}
                    material={materials["Cube_gift.005"]}
                  />
                </group>
                <group
                  name="Cube_gift004"
                  position={[-200, 100, -150]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube_gift004_Cube_gift004_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube_gift004_Cube_gift004_0.geometry}
                    material={materials["Cube_gift.004"]}
                  />
                </group>
                <group
                  name="Cube_gift003"
                  position={[-350, 200, -150]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube_gift003_Cube_gift003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube_gift003_Cube_gift003_0.geometry}
                    material={materials["Cube_gift.003"]}
                  />
                </group>
                <group
                  name="Cube_gift002"
                  position={[-350, 200, -50]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube_gift002_Cube_gift002_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube_gift002_Cube_gift002_0.geometry}
                    material={materials["Cube_gift.002"]}
                  />
                </group>
                <group
                  name="Cube_gift000"
                  position={[-350, 200, 150]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube_gift000_Cube_gift000_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube_gift000_Cube_gift000_0.geometry}
                    material={materials["Cube_gift.000"]}
                  />
                </group>
                <group
                  name="Camera"
                  position={[748.11, 534.37, 650.76]}
                  rotation={[Math.PI, 0.76, 2.68]}
                  scale={100}
                >
                  <group name="Object_19" />
                </group>
                <group
                  name="Gift000"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="Cube_gift001"
                  position={[-350, 200, 50]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube_gift001_Cube_gift001_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube_gift001_Cube_gift001_0.geometry}
                    material={materials["Cube_gift.001"]}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/stylised_gifts_christmas_-_animated.glb");
