/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";


import React, { Suspense, useEffect, useRef, useState } from "react";
import { Canvas, useFrame } from "@react-three/fiber";
import { OrbitControls, Sky, Cloud, Html } from "@react-three/drei";
import { MathUtils } from "three";
import "../src/index.css";
import { Howl } from "howler";
import { Physics, useBox, usePlane } from "@react-three/cannon";
import Modal from "./components/Modal/index";
import { init } from "@dimforge/rapier3d-compat";

export default function Model(props) {
  const { nodes, materials } = useGLTF("Tree.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        // castShadow
        // receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.Material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={46.32}
      />
      <mesh
        // castShadow
        // receiveShadow
        geometry={nodes.Icosphere003.geometry}
        material={materials["Material.001"]}
        position={[0.41, 6.35, -0.7]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={139.01}
      />
    </group>
  );
}

useGLTF.preload("/Tree.glb");
